In [1]:
from datasets.dataset_dict import DatasetDict
from datasets import Dataset
import evaluate

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split 


Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


In [ ]:
from huggingface_hub import notebook_login
# If below code does not work, copy and paste this code in the terminal: huggingface-cli login 
# then paste this read token: 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# It may not show up but still paste the token in and press enter


notebook_login()

## Inference

In [2]:
# # uncomment based on if you want to do EVENT, CAUSE, or, ACTION
training_label = 'EVENT'
# training_label = 'CAUSE'
# training_label = 'ACTION'

This is the code you should currently use. Just copy and paste the text in here and will will spit out a demo answer.

In [5]:
from transformers import pipeline, AutoTokenizer

# set up the pipeline
training_label = 'EVENT'
classifier = pipeline("text-classification", model=f"Chantland/HRAF_{training_label}_Demo", use_auth_token="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", tokenizer=AutoTokenizer.from_pretrained("distilbert-base-uncased"))

In [97]:
# sample inference ENTER TEXT IN HERE.
text = "What is meant by the flight to the Milky Way? We are told that behind the visible Milky Way there is another Milky Way, and this is the one the sorcerer visits in his dreams. It is like a kuntanka (tjurunga) and the medicine man walks along it. It is beautiful and smooth like the subincision opening. If the subincision opening were not beautiful and smooth the medicine man might stick there and his soul might never go back into his body. (52) Ibid., pp. 69, 70. ”"
tokenizer_kwargs = {'padding':True,'truncation':True,'max_length':512}

classifier(text, **tokenizer_kwargs)

[{'label': 'ABSENT', 'score': 0.5897043347358704}]

### Load datset <font color="red">(do not run more than 1 cell)</font>

#### Old Dataset (dataset this was trained on)

In [133]:
import pandas as pd
import numpy as np

# load the dataset (THIS IS WHERE YOU WOULD ENTER IN THE DATA YOU WANTED TO TEST!)
df = pd.read_excel("../RA_Cleaning/Culture_Coding_old.xlsx", header=[0,1], index_col=0)
# subdivide into just passage and outcome
df_small = pd.DataFrame()
df_small[["passage_ID","passage","label"]] = df[[('CULTURE', "Passage Number"), ('CULTURE', "Passage"), (training_label, "No_Info")]]
# Flip the label of "no_info"
df_small["label"] = df_small['label'].replace({0:1, 1:0})

# Remove certain passages which should not be in training or inference (these are duplicates that had to be manually found by a human)
values_to_remove = [3252, 33681, 6758, 10104]
df_small = df_small[~df_small['passage_ID'].isin(values_to_remove)]
df_small

# Create an NLP friendly dataset
Hraf = Dataset.from_dict(df_small.to_dict(orient= 'list'))
Hraf


Dataset({
    features: ['passage_ID', 'passage', 'label'],
    num_rows: 1747
})

#### New Codings: (Current Dataset - MINUS - Old Dataset)

In [129]:
# load OLD and new datasets (THIS IS WHERE YOU WOULD ENTER IN THE DATA YOU WANTED TO TEST!)
df_old = pd.read_excel("../RA_Cleaning/Culture_Coding_old.xlsx", header=[0,1], index_col=0)
df_current = pd.read_excel("../RA_Cleaning/Culture_Coding.xlsx", header=[0,1], index_col=0)

# Remove the runs not of the first from the datasets (this will be made superfluous later but nonetheless is an extra assuredness step)
# df_old = df_old.loc[df_old[("CODER","Run_Number")]==1] #if this had "Run_Number" column, you would uncomment and run this line
df_current = df_current.loc[df_current[("CODER","Run_Number")]==1]

# only get new rows that have NOT been trained/tested on before
df_new = pd.concat([df_current, df_old])
df_new = df_new[~df_new.duplicated(subset=("CULTURE","Passage Number"), keep=False)]


# subdivide into just passage and outcome
df_small = pd.DataFrame()
df_small[["passage_ID","passage","label"]] = df_new[[('CULTURE', "Passage Number"), ('CULTURE', "Passage"), (training_label, "No_Info")]]
# Flip the lable of "no_info"
df_small["label"] = df_small['label'].replace({0:1, 1:0})

# Remove certain passages which should not be in training or inference (these are duplicates that had to be manually found by a human)
values_to_remove = [3252, 33681, 6758, 10104]
df_small = df_small[~df_small['passage_ID'].isin(values_to_remove)]
df_small

# Create an NLP friendly dataset
Hraf = Dataset.from_dict(df_small.to_dict(orient= 'list'))
Hraf


Dataset({
    features: ['passage_ID', 'passage', 'label'],
    num_rows: 140
})

In [81]:
# df_small_CAUSE =  df_small.copy()
# sum(df_small['label'] != df_small_CAUSE['label'])
# df_small_CAUSE

### Predict The Dataset

In [140]:
# load a list of passages and predict them (will take about .25 seconds per passage for me so beware the wait)

HrafOutput = []
for text in Hraf:
    # text = Hraf[text]
    score = classifier(text['passage'], **tokenizer_kwargs)
    score[0]["actual_label"] = text['label']
    score[0]["passage"] = text['passage']
    score[0]["ID"] = text['passage_ID']

    # change the predicted label into a digit that we can compare
    if score[0]['label'] == 'PRESENT':
        score[0]['label'] = 1
    elif score[0]['label'] == 'ABSENT':
        score[0]['label'] = 0
    else:
        score[0]['label'] = 9


    # score[0][("actual_label", 'passage')] = text['passage'], text['label']
    HrafOutput.append(score[0])

In [141]:
HrafOutput

[{'label': 1,
  'score': 0.9905259609222412,
  'actual_label': 1,
  'passage': 'One time I had a dream in which a medicine woman came by and gave me some paint. She said if I would use this paint I would never get the smallpox. Some time after this the smallpox broke out among our people. My wife was very ill but in order to get away from the smallpox, I put her on a travois and started out. Finally, the travois broke down and we stopped to camp. While we were at this place, as I lay on the ground one day looking towards Sweet Grass Hills, I saw a star coming toward me. As it came along it left a path, one side of which was yellow, and the other blue. It passed directly over my head and then disappeared. As it went along it said, “I am the morningstar, I shall give you my power.” Now, this is why I wear the brass button on my robe, it represents the morningstar (50-4507).',
  'ID': 5153},
 {'label': 1,
  'score': 0.9913582801818848,
  'actual_label': 1,
  'passage': 'Cree medicines are

### Calculate "Correctness" Metrics

In [136]:
# Try preconstructed evaluations

# loading precision
precision = evaluate.load('precision')
result = precision.compute(predictions=[x['label'] for x in HrafOutput], references=[x['actual_label'] for x in HrafOutput])
# print(result)

# f1 score
from sklearn.metrics import f1_score, accuracy_score
accuracy = round(accuracy_score([x['actual_label'] for x in HrafOutput], [x['label'] for x in HrafOutput]),3)
f1 = round(f1_score([x['actual_label'] for x in HrafOutput], [x['label'] for x in HrafOutput], average = 'binary'),3)
f1_micro = round(f1_score([x['actual_label'] for x in HrafOutput], [x['label'] for x in HrafOutput], average='micro'),3)
f1_macro = round(f1_score([x['actual_label'] for x in HrafOutput], [x['label'] for x in HrafOutput], average='macro'),3)
print(f'Accuracy  {accuracy}\nF1 score (base)  {f1}\nF1 score (micro) {f1_micro}\nF1 score (macro) {f1_macro}')

Accuracy  0.951
F1 score (base)  0.972
F1 score (micro) 0.951
F1 score (macro) 0.888


#### Create Correctness Metric Myself
This was made before finding out we could just load preconstructed, but it is great for the confusion matrix!

In [57]:
# set up confusion matrix for calculating precision myself
confusionMatrix_dict = {"TruePos":0, "FalsePos":0, "FalseNeg":0, "TrueNeg":0}
for text in HrafOutput:
    if text['actual_label'] == 1:
        if text['label'] == 1:
            confusionMatrix_dict["TruePos"] += 1
        elif text['label'] == 0:
            confusionMatrix_dict["FalseNeg"] += 1
        else:
            raise Exception("ERROR pos")
    elif text['actual_label'] == 0:
        if text['label'] == 1:
            confusionMatrix_dict["FalsePos"] += 1
        elif text['label'] == 0:
            confusionMatrix_dict["TrueNeg"] += 1
        else:
            raise Exception("ERROR neg")
    else:
        raise Exception("ERROR actual")



In [58]:
confusionMatrix_dict

{'TruePos': 68, 'FalsePos': 28, 'FalseNeg': 2, 'TrueNeg': 42}

In [59]:
TP = confusionMatrix_dict['TruePos']
TN = confusionMatrix_dict['TrueNeg']
FP = confusionMatrix_dict['FalsePos']
FN = confusionMatrix_dict['FalseNeg']

In [61]:
# get scores 
precision = TP/ (TP + FP)
recall = TP/ (TP + FN)
F1 = (2 * precision * recall) / (precision + recall)
F1_test = TP/ (TP + .5*(FP + FN)) #done to double check work
MCC_num = (TP * TN) - (FP - FN)
MCC_denom = np.sqrt((TP + FN) * (TP + FN) * (TN + FP) * (TN + FN))
MCC = MCC_num / MCC_denom #mathews correlation coefficient

assert round(F1,5) == round(F1_test,5), ValueError
print(f'Precision:   {round(precision,3)}\nRecall:      {round(recall,3)}\nF1:          {round(F1,3)}\nMCC:         {round(MCC,3)}')

Precision:   0.708
Recall:      0.971
F1:          0.819
MCC:         0.728


## Optional File save

In [142]:
# optionally save the file to json
from transformers import AutoTokenizer
import copy

HrafOutput_dummy = copy.deepcopy(HrafOutput)

tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

def preprocess_function(examples):
    return tokenizer(examples["passage"], truncation=True)

tokenized_Hraf = Hraf.map(preprocess_function, batched=True)

for index, passage in enumerate(HrafOutput_dummy):
    assert passage['passage'] == tokenized_Hraf[index]['passage']
    passage['predicted_label'] = passage.pop('label') # rename label
    passage['actual_label'] = tokenized_Hraf[index]['label']
    passage['input_ids'] = tokenized_Hraf[index]['input_ids']

Map:   0%|          | 0/1747 [00:00<?, ? examples/s]

In [143]:
import json
# Save to unformatted json (uncomment)
with open(f"../Tokenized_Datasets/tokenized_Hraf_{training_label}.json", "w") as outfile:
    json.dump(HrafOutput_dummy, outfile)


# # Save to Dataset (uncomment)
# HrafOutput_dummy_dataset = Dataset.from_list(HrafOutput_dummy)
# Dataset.to_json(HrafOutput_dummy_dataset, f"../Tokenized_Datasets/tokenized_Hraf_{training_label}_Dataset")

## CHi Square

In [ ]:
df.head(3)

In [41]:
from scipy.stats import chi2_contingency

ct_EVENT_CAUSE = pd.crosstab(df[('EVENT','No_Info')], df[('CAUSE','No_Info')], rownames=['ACTION'], colnames=['CAUSE'])
ct_EVENT_CAUSE

array([[1167,  351],
       [  49,  183]], dtype=int64)

In [119]:
def chi_square_calc(row, col):
    cross_tab = pd.crosstab(df[(row,'No_Info')], df[(col,'No_Info')], rownames=[row], colnames=[col])
    stat, p, dof, expected = chi2_contingency(cross_tab)
    results = f"{row} by {col}:\nchi: {round(stat,1)}\np:   {round(p,3)}\n\n"
    return results

group_list = [('EVENT', 'CAUSE'), ('EVENT', 'ACTION'), ('ACTION', 'CAUSE')]
for row, col in group_list:
    print(chi_square_calc(row, col))

EVENT by CAUSE:
chi: 292.4
p:   0.0


EVENT by ACTION:
chi: 103.3
p:   0.0


ACTION by CAUSE:
chi: 0.0
p:   0.857




In [42]:
import numpy as np

x = np.array(ct_EVENT_CAUSE)
x

array([[1167,  351],
       [  49,  183]], dtype=int64)

In [44]:
def chi_sqr(obs):
    size_x = obs.shape
    chi_mat = np.zeros(size_x)
    for row in range(size_x[0]):
        for col in range(size_x[1]):
            exp = np.sum(x[row]) * np.sum(x[:,col]) / np.sum(x)
            chi_mat[row, col] = np.sum((obs[row, col] - exp)**2 / exp)
    return chi_mat




In [46]:
print(np.sum(chi_sqr(x)))

295.06544606349604


In [21]:
exp = np.sum(x[0]) * np.sum(x[:,0]) / np.sum(x)
np.sum((x - exp)**2 / exp)


1013.5716640866874

In [15]:
# (x[0] - x[1])**2 / x[1]
np.sum(x, axis=1)
np.sum(x, axis=0)

array([1216,  534])

In [7]:
(x - np.sum(x))**2 / np.sum(x)

array([[ 484.70914286, 1102.46914286],
       [1061.58228571, 1421.10228571]])